// build-meta.mjs — static SEO / social meta injector for GitHub Pages
//
// The site is client-rendered, so crawlers and link-preview bots see empty
// shells. This script reads assets/js/site-data.js (same trick as
// validate-data.mjs: stub `global.window` then require) and rewrites the
// <head> of every HTML shell in place, injecting a managed block between
//   <!-- meta:start --> ... <!-- meta:end -->
// so re-runs are idempotent. It also ensures each shell has <html lang="zh-CN">.
//
// Usage:  node scripts/build-meta.mjs      (run from the repository root)

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, dirname } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const BASE_URL = "https://aklycoh.github.io/travel/";

global.window = {};
const require = createRequire(import.meta.url);
require(join(root, "assets/js/site-data.js"));
const data = window.TRAVEL_DATA;

function esc(s) {
  return String(s)
    .replace(/\n/g, " ")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .trim();
}

function heroImageUrl(photoId) {
  const p = data.photos[photoId];
  if (!p) return `${BASE_URL}`;
  return `${BASE_URL}assets/images/${p.region}/large/${p.file}`;
}

// Absolute page URL for a shell path relative to repo root.
function pageUrl(relPath) {
  const dir = relPath.replace(/index\.html$/, "");
  return `${BASE_URL}${dir}`.replace(/\/+$/, "/");
}

// Derive per-page meta from the shell's body data attributes.
function metaFor(html, relPath) {
  const page = html.match(/data-page="([^"]+)"/)?.[1];
  const regionId = html.match(/data-region="([^"]+)"/)?.[1];
  const themeId = html.match(/data-theme="([^"]+)"/)?.[1];

  if (page === "home") {
    return {
      title: `${(data.home.title || "旅行记录").replace(/\n/g, "")} · Travel Notes`,
      description: data.home.deck,
      image: heroImageUrl(data.home.hero),
      type: "website"
    };
  }
  if (page === "region") {
    const region = data.regions.find((r) => r.id === regionId);
    return {
      title: `${region.title} · Travel Notes`,
      description: region.deck,
      image: heroImageUrl(region.hero),
      type: "website"
    };
  }
  if (page === "theme") {
    const region = data.regions.find((r) => r.id === regionId);
    const theme = data.themes[themeId];
    return {
      title: `${theme.title} · ${region.name} · Travel Notes`,
      description: theme.intro || theme.deck,
      image: heroImageUrl(theme.hero),
      type: "article"
    };
  }
  throw new Error(`Unknown page type in ${relPath}: ${page}`);
}

function buildBlock(meta, url) {
  const t = esc(meta.title);
  const d = esc(meta.description);
  const lines = [
    `<!-- meta:start (generated by scripts/build-meta.mjs — do not edit by hand) -->`,
    `<title>${t}</title>`,
    `<meta name="description" content="${d}">`,
    `<link rel="canonical" href="${url}">`,
    `<meta property="og:type" content="${meta.type}">`,
    `<meta property="og:title" content="${t}">`,
    `<meta property="og:description" content="${d}">`,
    `<meta property="og:image" content="${meta.image}">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:site_name" content="Travel Notes">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${t}">`,
    `<meta name="twitter:description" content="${d}">`,
    `<meta name="twitter:image" content="${meta.image}">`,
    `<!-- meta:end -->`
  ];
  return lines.join("\n    ");
}

async function htmlShells(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.name.startsWith(".") || entry.name === "_raw_photos" || entry.name === "node_modules") continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await htmlShells(path)));
    } else if (entry.isFile() && entry.name === "index.html") {
      files.push(path);
    }
  }
  return files;
}

const shells = await htmlShells(root);
let changed = 0;

for (const file of shells) {
  const relPath = relative(root, file);
  let html = await readFile(file, "utf8");
  const before = html;

  // 1. Ensure <html lang="zh-CN">.
  if (/<html(?![^>]*\blang=)/.test(html)) {
    html = html.replace(/<html\b/, '<html lang="zh-CN"');
  }

  // 2. Remove any existing managed block.
  html = html.replace(/\s*<!-- meta:start[\s\S]*?<!-- meta:end -->/g, "");

  // 3. Remove any stray <title> that lives outside the managed block so the
  //    generated one is authoritative and re-runs stay idempotent.
  html = html.replace(/[ \t]*<title>[\s\S]*?<\/title>\n?/g, "");

  // 4. Build and inject the block just before </head>.
  const meta = metaFor(html, relPath);
  const block = buildBlock(meta, pageUrl(relPath));
  html = html.replace(/([ \t]*)<\/head>/, `    ${block}\n$1</head>`);

  if (html !== before) {
    await writeFile(file, html);
    changed++;
    console.log(relPath);
  }
}

console.log(`Updated ${changed} of ${shells.length} shells.`);
