// process-images.mjs — responsive image tier generator (dependency-free)
//
// Generates the three web image tiers used by the site from the canonical
// `large` master JPEGs (which are themselves produced from `_raw_photos/` per
// AGENTS.md). For every `assets/images/<region>/large/<file>.jpeg` it produces:
//
//   large   ≤1800px longest side  (source of truth, left untouched here)
//   medium  ≤ 900px longest side  → assets/images/<region>/medium/<file>
//   thumb   ≤ 640px longest side  → assets/images/<region>/thumb/<file>
//
// It shells out to macOS `sips` (no npm deps). Existing tier files are rebuilt
// when their large master is newer; pass --force to rebuild everything.
// It also writes assets/js/image-widths.js from the actual JPEG dimensions so
// app.js can emit truthful srcset width descriptors.
//
// Usage:
//   node scripts/process-images.mjs            # all regions
//   node scripts/process-images.mjs chengdu    # one or more specific regions
//   node scripts/process-images.mjs --force    # ignore up-to-date checks
//   node scripts/process-images.mjs --manifest-only
//
// Run from the repository root.

import { readdir, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync, statSync } from "node:fs";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const run = promisify(execFile);
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = join(root, "assets", "images");
const manifestPath = join(root, "assets", "js", "image-widths.js");

const TIERS = {
  medium: 900,
  thumb: 640
};

const args = process.argv.slice(2);
const force = args.includes("--force");
const manifestOnly = args.includes("--manifest-only");
const regionArgs = args.filter((a) => !a.startsWith("--"));

// A destination is (re)built only when it is missing, or when --force is set.
// This keeps runs deterministic and avoids re-encoding (churning) tiers that
// already exist. Use --force to regenerate everything from the current large
// masters after replacing source images.
function needsBuild(src, dest) {
  return force || !existsSync(dest) || statSync(dest).mtimeMs < statSync(src).mtimeMs;
}

async function makeJpeg(src, dest, maxDim) {
  await run("sips", ["-s", "format", "jpeg", "-Z", String(maxDim), src, "--out", dest]);
}

function jpegWidth(buf) {
  if (buf.length < 4 || buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let off = 2;
  while (off < buf.length) {
    if (buf[off] !== 0xff) {
      off++;
      continue;
    }
    let marker = buf[off + 1];
    while (marker === 0xff) {
      off++;
      marker = buf[off + 1];
    }
    off += 2;
    if (marker === 0xd8 || marker === 0xd9 || (marker >= 0xd0 && marker <= 0xd7) || marker === 0x01) continue;
    if (off + 2 > buf.length) break;
    const len = buf.readUInt16BE(off);
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return buf.readUInt16BE(off + 5);
    }
    off += len;
  }
  return null;
}

async function processRegion(region) {
  const largeDir = join(imagesDir, region, "large");
  if (!existsSync(largeDir)) return { region, done: 0, skipped: 0 };

  const files = (await readdir(largeDir)).filter((f) => f.toLowerCase().endsWith(".jpeg"));
  let done = 0;
  let skipped = 0;

  for (const tier of Object.keys(TIERS)) {
    await mkdir(join(imagesDir, region, tier), { recursive: true });
  }

  for (const file of files) {
    const src = join(largeDir, file);

    for (const [tier, maxDim] of Object.entries(TIERS)) {
      const dest = join(imagesDir, region, tier, file);
      if (needsBuild(src, dest)) {
        await makeJpeg(src, dest, maxDim);
        done++;
      } else {
        skipped++;
      }
    }

  }

  return { region, done, skipped };
}

const regions = regionArgs.length
  ? regionArgs
  : (await readdir(imagesDir, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name);

if (!manifestOnly) {
  for (const region of regions) {
    const { done, skipped } = await processRegion(region);
    console.log(`${region}: ${done} generated, ${skipped} up to date`);
  }
}

const manifest = {};
for (const region of (await readdir(imagesDir, { withFileTypes: true })).filter((entry) => entry.isDirectory())) {
  const largeDir = join(imagesDir, region.name, "large");
  if (!existsSync(largeDir)) continue;
  for (const file of (await readdir(largeDir)).filter((name) => /\.jpe?g$/i.test(name)).sort()) {
    const widths = {};
    for (const tier of ["thumb", "medium", "large"]) {
      const path = join(imagesDir, region.name, tier, file);
      if (!existsSync(path)) continue;
      widths[tier] = jpegWidth(await readFile(path));
    }
    manifest[`${region.name}/${file}`] = widths;
  }
}

await writeFile(
  manifestPath,
  `// Generated by scripts/process-images.mjs. Do not edit by hand.\nwindow.TRAVEL_IMAGE_WIDTHS = {\n${Object.entries(manifest)
    .map(([key, widths]) => `  ${JSON.stringify(key)}: ${JSON.stringify(widths)}`)
    .join(",\n")}\n};\n`
);
console.log(`Image width manifest: ${Object.keys(manifest).length} entries`);
console.log("Done.");
